### ISSUE TITLE
cgtimer v1.1 work problem

### ISSUE THREAD

**Issue by ConstantineMnk** [jcalado/cgtimer#3]
Hey. I'm using your cgtimer. There is no timing during video playback from CasparCG.
CLIP TIME and REMANING CLIP TIME items do not work.
Tell me, maybe I'm doing something wrong?
I also tested on earlier versions of CasparCG- the problem was present.

Windows 10 x64 2004 last update

I use:
1. CasparCG Server v2.3.0 LTS Stable (last version server+client)
2. cgtimer-Setup-1.1.0.exe for Windows.
folder install (C:\Users\Constantine\AppData\Local\Programs\cgtimer\cgtimer.exe).

My config in casparcg.cgf
`<osc>`
`  <default-port>6250</default-port>`
`  <disable-send-to-amcp-clients>false [true|false]</disable-send-to-amcp-clients>`
`  <predefined-clients>`
`    <predefined-client>`
`      <address>127.0.0.1</address>`
`      <port>6251</port>`
`    </predefined-client>`
`  </predefined-clients>`
`</osc>`

Screenshot:
![Screenshot_6](https://user-images.githubusercontent.com/72627915/95625114-a37e7f00-0a80-11eb-85d1-3e017c2f960b.png)

**Comment by jcalado** [comment]
Did you get a windows permissions dialog like this?
![image](https://user-images.githubusercontent.com/26873/95630222-61057400-0a79-11eb-8ab2-854de1ec7213.png)

Also, please remove the line
`<disable-send-to-amcp-clients>false [true|false]</disable-send-to-amcp-clients>` **or** change it to
`<disable-send-to-amcp-clients>false</disable-send-to-amcp-clients>`

**Comment by jcalado** [comment]
Also, im assuming your server is running on 127.0.0.1.

**Comment by ConstantineMnk** [comment]
Thanks for the advice! Literally thirty minutes ago I figured it out.
The problem was:
`<disable-send-to-amcp-clients>false [true|false]</disable-send-to-amcp-clients>`
established "false"
